# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 20:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(help_text='employee id number', max_length=15)),
                ('object_id', models.CharField(blank=True, max_length=31, null=True)),
                ('processed_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('has_keyerrors', models.NullBooleanField()),
                ('keyerrors', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filing.xml_submission')),
            ],
        ),
    ]
