# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0002_processedfiling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedfiling',
            name='id',
        ),
        migrations.AlterField(
            model_name='processedfiling',
            name='object_id',
            field=models.CharField(max_length=31, primary_key=True, serialize=False),
        ),
    ]
