# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0003_auto_20170924_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfiling',
            name='is_saved',
            field=models.NullBooleanField(),
        ),
    ]
