# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0004_processedfiling_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xml_submission',
            name='as_json',
        ),
    ]
