# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0005_remove_xml_submission_as_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfiling',
            name='version_string',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='xml_submission',
            name='json_set',
            field=models.BooleanField(default=False, help_text='Has the json been set in ProcessedFiling?'),
        ),
    ]
